### ISSUE TITLE
template 변수를 찾을 수 없습니다

### ISSUE THREAD

**Issue by yiy0ung** [minuukang/uri-manager#1]
안녕하세요. 유용한 라이브러리를 만들어주셔서 감사합니다 :)

Read Me에 있는 예제 처럼 react-router에 template을 적용하려고 하였지만, `template` 변수를 찾지 못하고 타입에러가 발생하는 이슈가 있는 것 같습니다

![image](https://user-images.githubusercontent.com/38432821/131695613-50d3470a-da22-47b0-93be-3e7e32311571.png)

**Comment by minuukang** [comment]
늦게 답변드려서 죄송합니다. 이슈 남겨주셔서 감사합니다! `0.0.3` 에 해당 옵션을 추가했습니다. 감사합니다!
